### ISSUE TITLE
Not possible to change field type of existing field.

### ISSUE THREAD

**Issue by jensens** [plone/plone.schemaeditor#29]
User added a type with a bunch of textlines, but want to change it into text fields. This is not possible.

**Comment by pbauer** [comment]
This is not a bug but a feature-proposal. 
Since the fields settings (besides title, descrition and required) vary greatly between field-types it would probably result in removing the field and creating a new one with the same name and the same three basic settings. I don't see a huge benefit in this but it is a nice-to-have.

**Comment by davisagli** [comment]
This is easier to do for the specific textline -> text case mentioned, since they both store unicode strings so the values stored on existing instances don't need to be migrated. It's harder to do in general.
